#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pathlib import Path
import subprocess
import tempfile
import json

ASSEMBLIES_DIR = Path("/assemblies/")


class NotFoundError(Exception):
    pass


def load_genomes_file(filename):
    with open(filename, "r") as f:
        data = json.load(f)
    return data


def main():
    ASSEMBLIES_DIR.mkdir(parents=True, exist_ok=True)

    all_assemblies = []
    data = load_genomes_file("model-genome-clostr.json")

    for model_data in data["models"]:
        assembly = model_data["assembly"]
        all_assemblies.append(assembly)
    all_assemblies = list(set(all_assemblies))
    prepare_assembly_download(all_assemblies)
    download_assemblies()


def prepare_assembly_download(assemblies):
    (ASSEMBLIES_DIR / "README.md").unlink(missing_ok=True)
    (ASSEMBLIES_DIR / "md5sum.txt").unlink(missing_ok=True)
    (ASSEMBLIES_DIR / "ncbi_dataset" / "fetch.txt").unlink(missing_ok=True)
    with tempfile.TemporaryDirectory() as tmpdir:
        tmpfilename = Path(tmpdir) / "assemblies.txt"
        with open(tmpfilename, "w") as f:
            for assembly in assemblies:
                f.write(f"{assembly}\n")
        subprocess.run(
            [
                "datasets",
                "download",
                "genome",
                "accession",
                "--assembly-source",
                "RefSeq",
                "--include",
                "gbff",
                "--inputfile",
                str(tmpfilename),
                "--filename",
                str(ASSEMBLIES_DIR / "ncbi_dataset.zip"),
                "--dehydrated",
            ],
            input=(b"y\n" * 10),
        )
    subprocess.run(
        [
            "unzip",
            str(ASSEMBLIES_DIR / "ncbi_dataset.zip"),
            "-d",
            str(ASSEMBLIES_DIR),
        ]
    )
    (ASSEMBLIES_DIR / "ncbi_dataset.zip").unlink()


def download_assemblies():
    subprocess.run(
        ["datasets", "rehydrate", "--gzip", "--directory", str(ASSEMBLIES_DIR)]
    )


if __name__ == "__main__":
    main()
