#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pathlib import Path
import subprocess
import tempfile

ASSEMBLIES_DIR = Path("/assemblies/")


class NotFoundError(Exception):
    pass


def main():
    ASSEMBLIES_DIR.mkdir(parents=True, exist_ok=True)

    all_assemblies = []
    # with open("model-genome.tsv") as infile:
    with open("model-genome-small_set.tsv") as infile:
        for line in infile:
            if line.strip().startswith("#"):
                continue

            split = line.split("\t")
            if len(split) != 4:
                continue
            _, _, assembly_string, _ = split

            assemblies = [x.strip() for x in assembly_string.split(",")]
            all_assemblies.extend(assemblies)
    all_assemblies = list(set(all_assemblies))
    prepare_assembly_download(all_assemblies)
    download_assemblies()


def prepare_assembly_download(assemblies):
    with tempfile.TemporaryDirectory() as tmpdir:
        tmpfilename = Path(tmpdir) / "assemblies.txt"
        with open(tmpfilename, "w") as f:
            for assembly in assemblies:
                f.write(f"{assembly}\n")
        subprocess.run(
            [
                "datasets",
                "download",
                "genome",
                "accession",
                "--assembly-source",
                "RefSeq",
                "--include",
                "gbff",
                "--inputfile",
                str(tmpfilename),
                "--filename",
                str(ASSEMBLIES_DIR / "ncbi_dataset.zip"),
                "--dehydrated",
            ]
        )
    subprocess.run(
        [
            "unzip",
            str(ASSEMBLIES_DIR / "ncbi_dataset.zip"),
            "-d",
            str(ASSEMBLIES_DIR),
        ]
    )
    (ASSEMBLIES_DIR / "ncbi_dataset.zip").unlink()


def download_assemblies():
    subprocess.run(
        ["datasets", "rehydrate", "--gzip", "--directory", str(ASSEMBLIES_DIR)]
    )


if __name__ == "__main__":
    main()
