FROM python:3.7

RUN pip install scipy==1.3.0 swiglpk==4.65.1 python-libsbml-experimental==5.18.0 optlang==1.4.4 cobra==0.15.4
COPY ./convert_model.py ./convert_model.py

ENTRYPOINT ["python", "convert_model.py"]
