name: Download assemblies and upload all models as github artifact.

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Create .env file
        run: |
          echo "NCBI_API_KEY=${{secrets.BIGGR_NCBI_API_KEY}}" > .env
          echo "NCBI_EMAIL=${{secrets.BIGGR_NCBI_EMAIL}}" >> .env
      - name: Build docker image
        run: |
          docker compose build
      - name: Download previous artifact
        uses: actions/github-script@v6
        continue-on-error: true
        env:
          WORKFLOW_FILENAME: download-assemblies-upload-artifacts.yml
          ARTIFACT_NAME: model_genomes
          ARTIFACT_FILENAME: model_genomes.zip
          UNZIP_DIR: /data/biggr-assemblies/
        with:
          script: |
            const script = require('.github/scripts/download-previous-artifact.js')
            await script({github, context, core})
      - name: Run docker image
        run: |
          sudo mkdir -p /data/biggr-assemblies/
          docker compose up --exit-code-from biggr-data
      - name: Change permissions before upload
        run: |
          sudo chmod -R 775 /data
      - name: Upload genomes artifact
        uses: actions/upload-artifact@v4
        with:
          name: model_genomes
          path: /data/biggr-assemblies/
