name: Download genomes and upload all models + genomes to an azure blob.

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Create .env file
        run: |
          echo "NCBI_API_KEY=${{secrets.BIGGR_NCBI_API_KEY}}" > .env
          echo "NCBI_EMAIL=${{secrets.BIGGR_NCBI_EMAIL}}" >> .env
      - name: Build docker image
        run: |
          docker compose build
      - name: Run docker image
        run: |
          sudo mkdir -p /data/biggr-genbank/
          docker compose up --exit-code-from biggr-data
      - name: Upload genomes artifact
        uses: actions/upload-artifact@v4
        with:
          name: model_genomes
          path: /data/biggr-genbank/
