name: Download genomes and upload all models + genomes to an azure blob.

on:
  push:
    branches: [ pre-prod ]

jobs:
  build-and-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Create .env file
        run: |
          echo "NCBI_API_KEY=${{secrets.BIGGR_NCBI_API_KEY}}"
          echo "NCBI_EMAIL=${{secrets.BIGGR_NCBI_EMAIL}}"
      - name: Build docker image
        run: |
          docker compose build
